---

name: Publish image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Image tag
        required: true
        default: latest

jobs:
  build_and_push:
    name: Build and Push

    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Register timestamp tag
        run: echo "TIMESTAMP=$(date --utc +%Y%m%d%H%M%S)" >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GRU }}
          registry: ghcr.io
          repository: "${{ github.repository_owner }}/zonemaster-cli"
          tags: "${{ env.TIMESTAMP }}, ${{ github.event.inputs.tag }}"
