---

name: Publish image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Image tag
        required: true
        default: latest

jobs:
  build_and_push:
    name: Build and Push

    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Register timestamp tag
        run: echo "TIMESTAMP=$(date --utc +%Y%m%d%H%M%S)" >> "$GITHUB_ENV"

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GRU }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/zonemaster-cli:${{ env.TIMESTAMP }}
            ghcr.io/${{ github.repository_owner }}/zonemaster-cli:${{ github.event.inputs.tag }}
